### ISSUE TITLE
Minor incorrect syntaxes

### ISSUE THREAD

**Issue by 1N50MN14** [marko-js/marko-migrate#5] opened 2016-04-22 01:16 UTC
Going through the migrated templates, I encountered the following incorrect syntaxes:

`<span for="i from 1 to 4">` got translated to `<span 1 for(i from to 4)>`

`<mywgt value="" />` got translated to `<mywgt value />`

`<for each="key in data.keys"></for>` got translated to `<for(key in data.keys)></for(key>`

**Comment by patrick-steele-idem** [comment] 2016-05-09 21:52
I am not able to reproduce many of the issues with the current code. I'm those issues have been fixed with the latest code, but please let me know if you still see issues (although, I don't expect you to migrate again :) ). Thanks for reporting the problems!

**Closed as completed by patrick-steele-idem** 2016-05-09 21:52 UTC
